import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>All Wear App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2 className="text-[42px] font-[400] text-[#1D1F22] leading-relaxed">Category name</h2>
      </main>
    </>
  );
}
